/*

 CAN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char CAN[] =
{
  0x00,0x01,0x00,0x02,0x00,0x12,0x10,0x2A,
  0x38,0x44,0x70,0x88,0x20,0x50,0x00,0x20
};

/* End of CAN.C */
