/*

 FISH.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char FISH[] =
{
  0x00,0xF0,0xF0,0x0C,0xFC,0x02,0xFE,0x05,
  0xFE,0x01,0xFC,0x02,0xF0,0x0C,0x00,0xF0,
  0x00,0x08,0x08,0x15,0x1D,0x22,0x1F,0x20,
  0x1F,0x20,0x1D,0x22,0x08,0x15,0x00,0x08
};

/* End of FISH.C */
