/*

 ROD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char ROD[] =
{
  0x00,0x08,0x00,0x08,0x00,0x04,0x00,0x02,
  0x00,0x02,0x00,0x02,0x00,0x24,0x00,0x18,
  0x18,0x00,0x1C,0x08,0x1E,0x00,0x07,0x00,
  0x43,0x00,0xE7,0x00,0x7E,0x00,0x3C,0x00
};

/* End of ROD.C */
